name: Deploy Apache to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Verify kubeconfig file
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl config view

    - name: Apply Argo CD Application
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f k8s/argo-application.yml --validate=false