name: Deploy Apache to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Verify kubeconfig file
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl config view

    - name: List available contexts
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl config get-contexts

    - name: Set cluster context
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl config use-context kubernetes-admin@kubernetes

    - name: Verify cluster context
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl config current-context

    - name: Verify cluster endpoint
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl cluster-info

    - name: Apply Argo CD Application
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f k8s/argo-application.yml --validate=false